spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH:true}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}

  cache:
    type: redis

  redis:
    url: ${REDIS_URL:redis://localhost:6379}

server:
  port: ${PORT:8080}
  
jwt:
  secret:
    base64: ${JWT_SECRET}
  issuer: ${JWT_ISSUER:v-disk}
  ttl:
    seconds: ${JWT_TTL_SECONDS:3600}

front:
  baseurl: 'http://localhost:5173'

app:
  front:
    base-url: 'http://localhost:5173'
    verify-path: '/verify-email'
    reset-path: '/reset-password'
